#!/usr/bin/env python3
"""
fetch_data.py — Fetch SPY option chain or generate synthetic Heston data.

Tries yfinance first; falls back to synthetic data generated by solving
the Heston model with known parameters so the calibration has a verifiable
ground truth.

Output: data/spx_options_sample.csv
Columns: strike,expiry_years,market_price,market_iv,bid,ask,open_interest,type

Usage:
    python3 python/fetch_data.py
"""

import os
import sys
import math
import csv
import datetime
from typing import Optional

import numpy as np

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'spx_options_sample.csv')
CSV_HEADER = ['strike', 'expiry_years', 'market_price', 'market_iv',
              'bid', 'ask', 'open_interest', 'type']

# Known "ground truth" Heston parameters for synthetic generation
TRUE_PARAMS = dict(v0=0.04, kappa=1.5, theta=0.04, xi=0.3, rho=-0.7)

# ---------------------------------------------------------------------------
# Black-Scholes helpers
# ---------------------------------------------------------------------------

def _norm_cdf(x: float) -> float:
    """Standard normal CDF via erfc."""
    return 0.5 * math.erfc(-x / math.sqrt(2.0))


def bs_call(S: float, K: float, T: float, r: float, q: float, sigma: float) -> float:
    """Black-Scholes European call price."""
    if T <= 0 or sigma <= 0:
        return max(S * math.exp(-q * T) - K * math.exp(-r * T), 0.0)
    sqrt_T = math.sqrt(T)
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * sqrt_T)
    d2 = d1 - sigma * sqrt_T
    return S * math.exp(-q * T) * _norm_cdf(d1) - K * math.exp(-r * T) * _norm_cdf(d2)


def bs_vega(S: float, K: float, T: float, r: float, q: float, sigma: float) -> float:
    """Black-Scholes vega."""
    if T <= 0 or sigma <= 0:
        return 0.0
    sqrt_T = math.sqrt(T)
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * sqrt_T)
    return S * math.exp(-q * T) * math.exp(-0.5 * d1 ** 2) / math.sqrt(2 * math.pi) * sqrt_T


def bs_implied_vol(price: float, S: float, K: float, T: float,
                   r: float, q: float, tol: float = 1e-8) -> Optional[float]:
    """Newton-Raphson BS implied vol inversion with Brent fallback."""
    intrinsic = max(S * math.exp(-q * T) - K * math.exp(-r * T), 0.0)
    if price <= intrinsic - 1e-6 or price <= 0:
        return None
    sigma = 0.2
    for _ in range(100):
        p = bs_call(S, K, T, r, q, sigma)
        v = bs_vega(S, K, T, r, q, sigma)
        if v < 1e-12:
            break
        diff = p - price
        if abs(diff) < tol:
            return sigma
        sigma -= diff / v
        sigma = max(1e-4, min(sigma, 5.0))
    # Brent fallback
    lo, hi = 1e-4, 5.0
    if (bs_call(S, K, T, r, q, lo) - price) * (bs_call(S, K, T, r, q, hi) - price) > 0:
        return None
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if hi - lo < tol:
            return mid
        f_mid = bs_call(S, K, T, r, q, mid) - price
        f_lo  = bs_call(S, K, T, r, q, lo)  - price
        if f_lo * f_mid < 0:
            hi = mid
        else:
            lo = mid
    return 0.5 * (lo + hi)


# ---------------------------------------------------------------------------
# Heston characteristic function (Python, for synthetic data generation)
# ---------------------------------------------------------------------------

def heston_cf(u: complex, tau: float, S: float, r: float, q: float,
              v0: float, kappa: float, theta: float, xi: float, rho: float) -> complex:
    """
    Heston characteristic function (Albrecher et al. 2007 rotation-corrected form).
    Returns φ(u; τ) = exp(C + D·v₀ + i·u·ln(F))
    """
    iu = 1j * u
    beta = complex(kappa, 0) - complex(0, rho * xi) * u
    d = (beta ** 2 + xi ** 2 * (iu + u ** 2)) ** 0.5
    bmd = beta - d
    bpd = beta + d
    g = bmd / bpd
    edtau = np.exp(-d * tau)
    D = (bmd / xi ** 2) * (1 - edtau) / (1 - g * edtau)
    log_ratio = np.log((1 - g * edtau) / (1 - g))
    C = (kappa * theta / xi ** 2) * (bmd * tau - 2 * log_ratio)
    ln_F = math.log(S) + (r - q) * tau
    return np.exp(C + D * v0 + 1j * u * ln_F)


def heston_call_price(S: float, K: float, T: float, r: float, q: float,
                      v0: float, kappa: float, theta: float,
                      xi: float, rho: float) -> float:
    """
    Carr-Madan FFT pricing for one (K, T) using 4096-point FFT.
    Numerically integrates via Simpson's rule.
    """
    N = 4096
    eta = 0.25
    alpha = 1.5
    lam = 2 * math.pi / (N * eta)
    b = lam * N / 2
    F = S * math.exp((r - q) * T)

    # Carr-Madan (1999): k = ln(K), grid centred at ln(F)
    # X[u] = sum_j w_j * psi_j * exp(+iv_j*ln(F)) * (-1)^j * exp(-2pi*i*j*u/N)
    #       = sum_j w_j * psi_j * exp(-iv_j * k_u)   with k_u = ln(F)+(u-N/2)*lam

    v = np.arange(N) * eta
    u_damp = v - 1j * (alpha + 1)
    phi = np.array([heston_cf(u, T, S, r, q, v0, kappa, theta, xi, rho) for u in u_damp])

    denom_re = alpha ** 2 + alpha - v ** 2
    denom_im = (2 * alpha + 1) * v
    denom = denom_re + 1j * denom_im
    psi = np.exp(-r * T) * phi / denom

    # Simpson weights
    w = np.ones(N)
    w[1:-1:2] = 4
    w[2:-2:2] = 2
    w *= eta / 3

    ln_F = math.log(F)
    # Phase derivation: we want X[u] = Σ_j w_j ψ_j exp(-i·v_j·k_u)
    # with k_u = ln(F) + (u - N/2)·λ and np.fft.fft computing exp(-2πijk/N).
    # Substituting v_j = j·η, λ = 2π/(Nη):
    #   x[j] = w_j ψ_j · exp(-i·v_j·ln(F)) · (-1)^j
    j_arr = np.arange(N)
    phase = np.exp(-1j * v * ln_F) * ((-1.0) ** j_arr)
    fft_input = w * psi * phase

    fft_out = np.fft.fft(fft_input)

    # Log-strike grid: k_u = ln(F) + (u - N/2)*lam  = ln(K_u)
    k_grid = ln_F - b + lam * np.arange(N)
    exp_neg_alpha_k = np.exp(-alpha * k_grid)
    call_prices = exp_neg_alpha_k / math.pi * np.real(fft_out)

    # Interpolate to requested k = ln(K)
    k = math.log(K)
    idx = np.searchsorted(k_grid, k)
    if idx == 0:
        return max(float(call_prices[0]), 0.0)
    if idx >= N:
        return max(float(call_prices[-1]), 0.0)
    t = (k - k_grid[idx - 1]) / (k_grid[idx] - k_grid[idx - 1])
    price = (1 - t) * call_prices[idx - 1] + t * call_prices[idx]
    return max(float(price), 0.0)


# ---------------------------------------------------------------------------
# Synthetic data generation
# ---------------------------------------------------------------------------

def generate_synthetic_data() -> list[dict]:
    """
    Generate option chain using Heston model with known parameters.
    Returns list of dicts matching CSV_HEADER.
    """
    S = 100.0
    r = 0.05
    q = 0.02
    p = TRUE_PARAMS

    print(f"Generating synthetic data with true Heston parameters:")
    print(f"  v0={p['v0']}, kappa={p['kappa']}, theta={p['theta']}, "
          f"xi={p['xi']}, rho={p['rho']}")
    print(f"  (sigma_0={math.sqrt(p['v0']):.1%}, sigma_inf={math.sqrt(p['theta']):.1%})")

    rows = []
    expiries_years = [0.083, 0.25, 0.5, 1.0]  # ~1M, 3M, 6M, 12M
    n_strikes = 12

    for T in expiries_years:
        F = S * math.exp((r - q) * T)
        strikes = [F * (0.80 + 0.40 * i / (n_strikes - 1)) for i in range(n_strikes)]

        for K in strikes:
            try:
                price = heston_call_price(S, K, T, r, q, **p)
                iv = bs_implied_vol(price, S, K, T, r, q)
                if iv is None or iv <= 0.01 or iv > 1.0:
                    continue

                spread_pct = 0.02  # 2% synthetic spread
                mid = price
                bid = mid * (1 - spread_pct)
                ask = mid * (1 + spread_pct)

                rows.append({
                    'strike':       round(K, 4),
                    'expiry_years': round(T, 6),
                    'market_price': round(mid, 6),
                    'market_iv':    round(iv, 6),
                    'bid':          round(bid, 6),
                    'ask':          round(ask, 6),
                    'open_interest': 1000,
                    'type':          0,   # call
                })
            except Exception as e:
                print(f"  Warning: skipping K={K:.2f} T={T:.3f}: {e}")

    return rows


# ---------------------------------------------------------------------------
# Market data fetcher (yfinance)
# ---------------------------------------------------------------------------

def fetch_market_data() -> list[dict]:
    """Fetch real SPY option chain via yfinance."""
    try:
        import yfinance as yf
        print("Fetching SPY option chain via yfinance...")
        spy = yf.Ticker("SPY")
        S = spy.fast_info.get('lastPrice') or spy.info.get('currentPrice', 500.0)
        r = 0.05  # approximate risk-free rate
        q = 0.015 # approximate SPY dividend yield

        expirations = spy.options[:4]  # next 4 expiries
        today = datetime.date.today()
        rows = []

        for exp_str in expirations:
            exp_date = datetime.date.fromisoformat(exp_str)
            T = (exp_date - today).days / 365.25

            if T < 0.05:  # skip very near expiry
                continue

            chain = spy.option_chain(exp_str)

            for opt_type, df in [('call', chain.calls), ('put', chain.puts)]:
                for _, row in df.iterrows():
                    K = float(row['strike'])
                    bid = float(row.get('bid', 0) or 0)
                    ask = float(row.get('ask', 0) or 0)
                    oi = float(row.get('openInterest', 0) or 0)
                    iv_raw = float(row.get('impliedVolatility', 0) or 0)
                    mid = 0.5 * (bid + ask)

                    # Liquidity filter
                    if oi < 500 or bid <= 0 or mid <= 0:
                        continue
                    if K / S < 0.80 or K / S > 1.20:
                        continue
                    if (ask - bid) / mid > 0.10:
                        continue

                    # Re-compute IV from mid price (more accurate than yfinance's)
                    iv = None
                    if opt_type == 'call':
                        iv = bs_implied_vol(mid, S, K, T, r, q)
                    else:
                        # Convert put to call via P-C parity
                        call_equiv = mid + S * math.exp(-q * T) - K * math.exp(-r * T)
                        call_equiv = max(call_equiv, 0.0)
                        iv = bs_implied_vol(call_equiv, S, K, T, r, q)

                    if iv is None or iv <= 0.005 or iv > 2.0:
                        # Fall back to yfinance IV
                        iv = iv_raw if iv_raw > 0 else None
                    if iv is None:
                        continue

                    rows.append({
                        'strike':        round(K, 4),
                        'expiry_years':  round(T, 6),
                        'market_price':  round(mid, 6),
                        'market_iv':     round(iv, 6),
                        'bid':           round(bid, 6),
                        'ask':           round(ask, 6),
                        'open_interest': int(oi),
                        'type':          0 if opt_type == 'call' else 1,
                    })

        print(f"Fetched {len(rows)} liquid SPY options.")
        return rows

    except ImportError:
        print("yfinance not installed (pip install yfinance).  Using synthetic data.")
        return []
    except Exception as e:
        print(f"yfinance fetch failed: {e}\nFalling back to synthetic data.")
        return []


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    rows = fetch_market_data()

    if not rows:
        rows = generate_synthetic_data()

    with open(OUTPUT_PATH, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=CSV_HEADER)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    print(f"\nWrote {len(rows)} options to {OUTPUT_PATH}")
    print("\nSample rows:")
    for row in rows[:3]:
        print(f"  {row}")


if __name__ == '__main__':
    main()
